services:
  mongodb:
    image: mongo
    container_name: tomadb
    ports:
      - "30000:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-seed:/docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_DATABASE: tomafinaldb

  backend: 
    build:
      context: ./back
    container_name: tomabackend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/tomafinaldb
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./front
    container_name: tomafrontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo-data:
